blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
	path('', views.PostListView.as_view(), name = 'home'),
	path('post/<int:pk>/', views.PostDetailView.as_view(), name = 'post_detail'),
	path('post/new/', views.PostCreateView.as_view(), name = 'post_create'),
	path('post/<int:pk>/update/', views.PostUpdateView.as_view(), name = 'post_update'),
	path('post/<int:pk>/delete/', views.PostDeleteView.as_view(), name = 'post_delete'),
]

django_project/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from users import views as users_view

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('', include('users.urls')),
    path('sign-up/', users_view.sign_up, name = 'sign_up'),
    path('login/', auth_views.LoginView.as_view(template_name = "users/login.html"), name = 'login'),
    path('logout/', auth_views.LogoutView.as_view(template_name = "blog/home.html"), name = 'logout'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('profile/', views.profile_view, name = 'profile'),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.
class Post(models.Model):
	title = models.CharField(max_length = 100)
	content = models.TextField()
	date_posted = models.DateTimeField(auto_now_add = True)
	date_updated = models.DateTimeField(null = True, blank = True)
	author = models.ForeignKey(User, on_delete = models.CASCADE)
	is_updated_once = models.BooleanField(default = False)
	
	def get_absolute_url(self):
		return reverse('blog:post_detail', kwargs = {'pk' : self.pk})

users/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image

# Create your models here.
class Profile(models.Model):
	user = models.OneToOneField(User, on_delete = models.CASCADE)
	image = models.ImageField(default = 'default.jpg', upload_to = 'profile_pics')

	def __str__(self):
		return f'{self.user.username} Profile'

	def save(self):
		super().save()
		img = Image.open(self.image.path)
		if(img.height > 300 or img.width > 300):
			output_size = (300, 300)
			img.thumbnail(output_size)
			img.save(self.image.path)

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from . models import Profile

class SignUpForm(UserCreationForm):
	email = forms.EmailField()

	class Meta:
		model = User
		fields = ['username', 'email', 'password1', 'password2']


class UserUpdateForm(forms.ModelForm):
	email = forms.EmailField()

	class Meta:
		model = User
		fields = ['username', 'email']

class ProfileUpdateForm(forms.ModelForm):
	class Meta:
		 model = Profile
		 fields = ['image']

blog/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.urls import reverse


from . models import Post

from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
import datetime

# Create your views here.
class PostListView(ListView):
	model = Post
	template_name = "blog/home.html"
	context_object_name = 'posts'
	ordering = ['-date_posted']
	paginate_by = 5
	


class PostDetailView(DetailView):
	model = Post
	template_name = 'blog/post_detail.html'


class PostCreateView(LoginRequiredMixin, CreateView):
	model = Post
	fields = ['title', 'content']
	template_name = 'blog/post_create.html'

	def form_valid(self, form):
		form.instance.author = self.request.user
		return super().form_valid(form)


class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
	model = Post
	fields = ['title', 'content']
	template_name = 'blog/post_create.html'

	def test_func(self):
		post = self.get_object()
		return post.author == self.request.user

	def form_valid(self, form):
		form.instance.date_updated = datetime.datetime.now()
		form.instance.author = self.request.user
		form.instance.is_updated_once = True
		return super().form_valid(form)


class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
	model = Post
	template_name = 'blog/post_confirm_delete.html'

	def test_func(self):
		post = self.get_object()
		return post.author == self.request.user

	def get_success_url(self):
		return reverse('blog:home')

users/views.py
from django.shortcuts import render, redirect
from . forms import SignUpForm, UserUpdateForm, ProfileUpdateForm
from . models import Profile
from django.contrib import messages
from django.contrib.auth.decorators import login_required
# Create your views here.

def sign_up(request):

	if(request.method == 'POST'):
		form = SignUpForm(request.POST)
		if(form.is_valid()):
			form.save()
			username = form.cleaned_data['username']
			messages.success(request, f'Your account has been created! Try to login now')
			return redirect('login')
	else:
		form = SignUpForm()
	context = {
		'form' : form,
	}

	return render(request, 'users/register.html', context)

@login_required
def profile_view(request):

	#To check what is sent in request object
	# print("Logged in : ", (request.user).__dict__)
	profile_obj = Profile.objects.get(user = request.user)
	print(profile_obj) # Checking if the correct user is grabbed or not

	u_form = UserUpdateForm(request.POST, instance = request.user)
	p_form = ProfileUpdateForm(request.POST, request.FILES, instance = profile_obj)

	if(request.method == 'POST'):
		if(u_form.is_valid() and p_form.is_valid()):
			u_form.save()
			p_form.save()
			messages.success(request, "Your account has been updated")
			return redirect('profile')
	else:
		u_form = UserUpdateForm(instance = request.user)
		p_form = ProfileUpdateForm(instance = profile_obj)

	context = {
		'u_form' : u_form,
		'p_form' : p_form,
	}

	return render(request, 'users/profile.html', context)

blog/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
    <meta charset="utf-8">
	 <meta name="viewport" content="width=device-width, initial-scale=1">
	 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
	 <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
	 <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
	 <link rel="stylesheet" type="text/css" href="{% static 'blog/main.css' %}">

	<title> 
		{% if title != null %}
			title
		{% else %}
			Django Blog
		{% endif %}
	</title>
</head>
<body>
	{% include 'blog/navbar.html' %}

	{% if messages %}
	  	{% for message in messages %}
	  	<div class="row" style="padding-left: 145px;">
	    	<div class="col-md-8">
		  		<div class="alert alert-{{ message.tags }}" role="alert">
		  			{{ message }}
		  		</div>
		  	</div>
	  	</div>
	  	{% endfor %}
  	{% endif %}

	<main role="main" class="container">
	  <div class="row" style="padding-left: 53px;">
	    <div class="col-md-8">
	      {% block content %}{% endblock %}
	    </div>
	    <div class="col-md-4">
	      <div class="content-section">
	        <h3>Our Sidebar</h3>
	        <p class='text-muted'>You can put any information here you'd like.
	          <ul class="list-group">
	            <li class="list-group-item list-group-item-light">Latest Posts</li>
	            <li class="list-group-item list-group-item-light">Announcements</li>
	            <li class="list-group-item list-group-item-light">Calendars</li>
	            <li class="list-group-item list-group-item-light">etc</li>
	          </ul>
	        </p>
	      </div>
	    </div>
	  </div>
	</main>

</body>
</html>

blog/templates/blog/about.html
{% extends 'base.html' %}

{% block content %}
	About Page
{% endblock content %}

blog/templates/blog/home.html
{% extends 'base.html' %}

{% block content %}
	{% for post in posts %}
		<article class="media content-section">
		  <div class="media-body">
		    <div class="article-metadata">
		      <a class="mr-2" href="#">{{ post.author }}</a>
		      <small class="text-muted">{{ post.date_posted | date:'d F, Y' }}</small>
		    </div>
		    <h2><a class="article-title" href="{% url 'blog:post_detail' pk=post.id%}">{{ post.title }}</a></h2>
		    <p class="article-content">{{ post.content }}</p>
		  </div>
		</article>
	{% endfor %}

		{% if page_obj.has_previous %}
			<a class="btn btn-primary" href="?page={{ page_obj.previous_page_number }}">Previous</a>
		{% endif %}

		{% if page_obj.has_next %}
	     	<a class="btn btn-primary" href="?page={{ page_obj.next_page_number }}">Next</a>
	    {% endif %}
    <br><br>
{% endblock content %}

blog/templates/blog/main.html
<main role="main" class="container">
  <div class="row">
    <div class="col-md-8">
      {% block content %}{% endblock %}
    </div>
    <div class="col-md-4">
      <div class="content-section">
        <h3>Our Sidebar</h3>
        <p class='text-muted'>You can put any information here you'd like.
          <ul class="list-group">
            <li class="list-group-item list-group-item-light">Latest Posts</li>
            <li class="list-group-item list-group-item-light">Announcements</li>
            <li class="list-group-item list-group-item-light">Calendars</li>
            <li class="list-group-item list-group-item-light">etc</li>
          </ul>
        </p>
      </div>
    </div>
  </div>
</main>

blog/templates/blog/navbar.html
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">WebSiteName</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="{% url 'blog:home' %}">Home</a></li>
      <li><a href="{% url 'blog:post_create' %}">Blog Entry</a></li>
      <li><a href="#">About</a></li>
    </ul>

    <ul class="nav navbar-nav navbar-right">
      {% if user.is_authenticated%}
        <li><a href="{% url 'profile' %}"></span> {{ user.username }}</a></li>
        <li><a href="{% url 'logout' %}"><span class="glyphicon glyphicon-log-out"></span> Logout</a></li>
      {% else %}
        <li><a href="{% url 'sign_up' %}"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
        <li><a href="{% url 'login' %}"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
      {% endif %}
    </ul>

  </div>
</nav>
<br>

blog/templates/blog/post_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
	 <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Delete Post</legend>
                <h2>Are you sure you want to delete the post "{{ object.title }}"</h2>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit">Yes, Delete</button>
                <a class="btn btn-outline-secondary" href="{% url 'blog:post_detail' object.id %}">Cancel</a>
            </div>
        </form>
    </div>
{% endblock content %}

blog/templates/blog/post_create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
	<h2>Blog Post</h2><br>
	<form method="post">
		{% csrf_token %}
		{{ form|crispy }}
		<button type="submit">Submit </button> 
	</form>
	<br>
	<br>
	
{% endblock %}

blog/templates/blog/post_detail.html
{% extends 'base.html' %}

{% block content %}
	<article class="media content-section">
		<img class="img-circle account-img" src="{{ object.author.profile.image.url }}" >
	  <div class="media-body">
	    <div class="article-metadata">
	      <a class="mr-2" href="#">{{ object.author }}</a> <br>
	      <small class="text-muted">Date posted : {{ object.date_posted | date:'d F, Y' }}</small> <br>
	      {% if object.is_updated_once %}
	      	<small class="text-muted">Last updated : {{ object.date_updated | date:'d F, Y' }}
	      {% endif %}
	    </div>

	    <h2>{{ object.title }}
	    {% if object.author == user %}
            <a class="btn btn-primary btn-sm mt-1 mb-1" href="{% url 'blog:post_update' object.id %}">Update</a>
            <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'blog:post_delete' object.id %}">Delete</a>
        {% endif %}
        </h2>

        <br>
	    <p class="article-content">{{ object.content }}</p>
	  </div>
	</article>
{% endblock content %}

users/templates/users/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
	<h2>Log In</h2>
	<form method="post">
		{% csrf_token %}
		{{ form|crispy }}
		<button type="submit">Login </button> <a href="#" style="padding-left: 30px"> Forgot Password?</a>
	</form>
	<br>

	<div class="border-top pt-3">
		<small class="text-muted">
			Need have an account? <a href="#" class="ml-2">Sign Up</a>
		</small>
	</div>

	<br>
	
{% endblock %}

users/templates/users/logout.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
	<h2>Log In</h2>
	<form method="post">
		{% csrf_token %}
		{{ form|crispy }}
		<button type="submit">Login</button>
	</form>
	<a href="{% url 'password_reset' %}">Forgot Password?</a>
{% endblock %}

users/templates/users/profile.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
      <div class="media">
      	<div class="media-left">
        	<img class="img-circle account-img" src="{{ user.profile.image.url }}" >
    	</div>

        <div class="media-body">
          <h2 class="media-heading">{{ user.username }}</h2>
          <h4 class="text-secondary">{{ user.email }}</h4>
        </div>
      </div>

      <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Update Profile</legend>
            {{ u_form|crispy}}
            {{ p_form|crispy}}
        </fieldset>

        <div class="form-group">
          <button type="submit" class="btn btn-info">Update</button>
        </div>  
      </form>

    </div>
{% endblock content %}

users/templates/users/register.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
	<div class="content-section">
		<form method="POST">
			{% csrf_token %}
			<fieldset class="form-group">
				<legend class="border-bottom mb-4">Sign Up</legend>
				{{ form|crispy}}
			</fieldset>

			<div class="form-group">
				<button type="submit" class="btn btn-outline-info">Submit</button>
			</div>	
		</form>

		<div class="border-top pt-3">
			<small class="text-muted">
				Already have an account? <a href="#" class="ml-2">Log In</a>
			</small>
		</div>
	</div>
{% endblock content %}